# Generated by Django 5.0.2 on 2024-03-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_licenseidno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storename',
        ),
    ]
