# Generated by Django 5.0.2 on 2024-05-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review_bestfeatures_review_performance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
