# Generated by Django 5.0.2 on 2024-05-14 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ewallet_remove_order_checkout_remove_order_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=255)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ewallet')),
            ],
        ),
    ]
