# Generated by Django 5.0.2 on 2024-05-14 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderstatus', models.TextField(max_length=255)),
                ('total_amount', models.TextField(max_length=255)),
                ('order_date', models.CharField(max_length=255)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.checkout')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
